#!/bin/sh
set -e

# Input: Static huffman table from RFC 7541 without empty lines
# or page boundaries (huffcodes.txt).
# Lines beginning with "#" in the input are ignored.

grep -v '^#' |
sed -e 's,.\{48\} \+\([0-9a-f]\+\)  \[ \?\([0-9]\+\)\],\1\, \2,' |
awk -F' ' "
BEGIN { print \"// This file is generated by make-etable.sh\n\"
        print \"#include \\\"encode-table.h\\\"\n\"
        print \"const struct encv etable[256] = {\" }
NR <= 256 { printf \"    { 0x%-9s %2s },\\n\", \$1, \$2 }
END { print \"};\" }"
